config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
                     sessions: 'users/sessions',
                     registrations: 'users/registrations',
                     confirmations: 'users/confirmations',
                     passwords: 'users/passwords',
                     unlocks: 'users/unlocks',
                     omniauth_callbacks: 'users/omniauth_callbacks'
                   }

  # Subdomains are currently not available on heroku
  #constraints(subdomain: /.+/) do
    #get '/:url', to: 'frontend/case_studies#show', by_domain: true
    #get '*path' => redirect('/')
  #end

  # For redirect after sign in
  get 'case_studies' => 'backend/case_studies#index', as: :user_root

  concern :publishable do
    post :publish, on: :member
  end

  concern :approvable do
    post :approve, on: :member
  end

  resources :case_studies, controller: 'backend/case_studies',
            path_names: { edit: 'edit(/:step)' },
            concerns: :publishable do
    #collection do
    #  post :add_image, :add_template
    #end
  end

  resources :testimonials, controller: 'backend/testimonials',
            :concerns => [:publishable, :approvable]

  resources :reviews, controller: 'backend/reviews',
            :concerns => [:publishable, :approvable]

  resources :requests, controller: 'backend/requests', :only => [:index, :destroy]

  match '/requests/new_testimonial' => 'backend/requests#new_testimonial',
    :via => :get, :as => :new_testimonial_request
  match '/requests/create_testimonial' => 'backend/requests#create_testimonial',
    :via => :post, :as => :create_testimonial_request

  match '/requests/new_review' => 'backend/requests#new_review',
    :via => :get, :as => :new_review_request
  match '/requests/create_review' => 'backend/requests#create_review',
    :via => :post, :as => :create_review_request

  match '/testimonial/request/new/:token' => 'backend/requests#new_customer_testimonial',
    :via => :get, :as => :new_customer_testimonial
  match '/testimonial/request/:token' => 'backend/requests#create_customer_testimonial',
    :via => :post, :as => :create_customer_testimonial

  match '/review/request/new/:token' => 'backend/requests#new_customer_review',
    :via => :get, :as => :new_customer_review
  match '/review/request/:token' => 'backend/requests#create_customer_review',
    :via => :post, :as => :create_customer_review

  resources :templates, controller: 'backend/templates'

  # embedding routes
  match '/render_tile/:id' => 'frontend/case_studies#tile', via: [:get, :options]
  match '/render_testimonial/:id' => 'frontend/case_studies#testimonial', via: [:get, :options]

  get ':user_url' => 'frontend/case_studies#index', as: :public_case_studies
  get ':user_url/code' => 'frontend/case_studies#code', as: :code_case_studies
  get ':user_url/:url' => 'frontend/case_studies#show', as: :public_case_study

  root 'backend/home#index'
end

app/controllers/backend/application_controller.rb
module Backend
  class ApplicationController < ::ApplicationController
    before_filter :authenticate_user!
  end
end

app/controllers/backend/case_studies_controller.rb
class Backend::CaseStudiesController < Backend::ApplicationController
  #include Wicked::Wizard
  before_action :set_case_study, except: [:index, :new, :create]
  #steps :template, :content, :tile_template, :tile_content

  def index
    @case_studies = current_user.case_studies.all
  end

  def new
    @case_study = CaseStudy.new
  end

  def main
    wizard_save(nil, next: :logo, back: :edit)
  end

  def logo
    @case_study.update(case_study_params) if case_study_params
    wizard_save(:validate_logo, next: :template, back: :logo)
  end

  def template
    if case_study_params[:template_id]
      @case_study.insert_template CaseStudyTemplate
                                      .find(case_study_params[:template_id]).template
    end
    wizard_save(:validate_template, next: :content, back: :template)
  end

  def content
    @case_study.update(case_study_params) if case_study_params
    #wizard_save(:validate_template, next: :tile_template, back: :content)
    @case_study.next_step
    @case_study.insert_tile TileTemplate.take.template # temp we have one tile template
    redirect_to case_study_path(@case_study), notice: 'Case study created!'
  end

  def tile_template
    # TBD
  end

  def tile_content
    # TBD
  end

  def create
    @case_study = current_user.case_studies.new(case_study_params)
    wizard_save(nil, next: :logo, back: :new)
  end

  def show
    redirect_to case_studies_path, alert: 'Case study is not finished' unless @case_study.ready?
  end

  def edit
    params[:step] ||= @case_study.ready? ? :content : @case_study.step
    render params[:step]
  end

  def update
    send(params[:step]) if params[:step].present?
  end

  def destroy
    redirect_to case_studies_path, notice: 'Case study destroyed' if @case_study.destroy
  end

  #def add_template
  #  template = Nokogiri::HTML(params[:template].read)
  #  template.css('script,iframe').remove
  #  @template = template.to_s
  #  @editor_index =  %w(case_study tile).find_index(params[:type])
  #  respond_to :js
  #end

  def publish
    @case_study.toggle_published
    redirect_to case_studies_path,
                notice: "Case study was #{'un' unless @case_study.published? }published"
  end

  protected

  def set_case_study
    @case_study = CaseStudy.find(params[:id])
  end

  def case_study_params
    if params[:case_study].present? && params[:case_study].any?
      params.require(:case_study).permit(:image, :client, :title, :template_id,
                                         :template_content, :tile_template_content)
    end
  end

  def wizard_save(validation, args = {})
    if (validation ? send(validation, @case_study) : true) && @case_study.save
      @case_study.next_step
      redirect_to edit_case_study_path(@case_study, step: args[:next])
    else
      render args[:back]
    end
  end

  private

  def validate_logo(cs)
    cs.errors[:image] << 'should be uploaded' unless cs.image.present?
    cs.errors.empty?
  end

  def validate_template(cs)
    cs.errors[:template_content] << 'should be choosen' unless cs.template_content.present?
    cs.errors.empty?
  end

end

app/controllers/backend/home_controller.rb
class Backend::HomeController < ApplicationController
  def index
    # overview page
  end
end

app/controllers/backend/requests_controller.rb
class Backend::RequestsController < ApplicationController
  #has_scope :page, default: 1
  before_action :init_request, :only => [:new_testimonial, :new_review]



  def create_testimonial
    @request = current_user.requests.new(request_params)
    @request.request_type = :testimonial

    if @request.save
      @request.send_mail
      redirect_to requests_path, :notice => 'Request for Testimonial sent'
    else
      @testimonial = Testimonial.new
      @templates = TestimonialTemplate.all
      render 'backend/testimonials/new'
    end
  end

  def create_review
    @request = current_user.requests.new(request_params)
    @request.request_type = :review

    if @request.save
      @request.send_mail
      redirect_to requests_path, :notice => 'Request for Review sent'
    else
      @review = Review.new
      render 'backend/reviews/new'
    end
  end

  def index
    @requests = current_user.requests.order('created_at DESC')
  end

  def destroy
    @request = current_user.requests.find params[:id]
    redirect_to requests_path, notice: 'Request destroyed' if @request.destroy
  end

  def new_customer_testimonial
    @request = Request.find_by_token params[:token]
    if @request && @request.status == 'sent'
      @testimonial =
        Testimonial.new :name => @request.name, :request_token => params[:token]
      @templates = TestimonialTemplate.all
    else
      redirect_to testimonials_path, :notice => 'Testimonial created'
    end
  end

  def new_customer_review
    @request = Request.find_by_token params[:token]
    if @request && @request.status == 'sent'
      @review =
        Review.new :name => @request.name, :request_token => params[:token]
    else
      redirect_to reviews_path, :notice => 'Review created'
    end
  end

  def create_customer_testimonial
    @request = Request.find_by_token params[:token]
    @user = @request.user
    @testimonial = @user.testimonials.new(testimonial_params)

    if @testimonial.save
      # @request.testimonial = @testimonial
      @request.update_attributes :status => 'Filled by customer'
      redirect_to testimonials_path, :notice => 'Thank you for your feedback!' # later thanks page
    else
      @templates = TestimonialTemplate.all
      render :new_customer_testimonial
    end
  end

  def create_customer_review
    @request = Request.find_by_token params[:token]
    @user = @request.user
    @review = @user.reviews.new(review_params)

    if @review.save
      # @request.review = @review
      @request.update_attributes :status => 'Filled by customer'
      redirect_to reviews_path, :notice => 'Thank you for your feedback!' # later thanks page
    else
      render :new_customer_review
    end
  end

  private

  def init_request
    @request =
      Request.new :sender => current_user.name, :reply_to => current_user.email
  end

  def testimonial_params
    params.require(:testimonial).permit(:image, :name, :role, :company, :content, :template_id)
  end

  def review_params
    params.require(:review).permit(:image, :name, :role, :company, :content, :title, :rating)
  end

  def request_params
    params.require(:request).
      permit(:name, :email, :sender, :reply_to, :subject, :message)
  end

end

app/controllers/backend/reviews_controller.rb
class Backend::ReviewsController < ApplicationController
  before_action :set_review, except: [:index, :new, :create]

  def index
    @reviews = current_user.reviews.order('created_at DESC')
  end

  def new
    @review = Review.new
    @request =
      Request.new :sender => current_user.name, :reply_to => current_user.email
  end

  def create
    @review = current_user.reviews.new(review_params)

    if @review.save
      redirect_to reviews_path, :notice => 'Review created'
    else
      @request =
        Request.new :sender => current_user.name, :reply_to => current_user.email
      render :new
    end
  end

  def edit
    @review = Review.find params[:id]
  end

  def update
    if @review.update(review_params)
      redirect_to reviews_path, :notice => 'Review updated'
    else
      render :edit
    end
  end

  def destroy
    if @review.destroy
      redirect_to reviews_path, :notice => 'Review destroyed'
    end
  end

  # def publish
  #   @testimonial.toggle(:published).save
  #   if @testimonial.testimonial_request && @testimonial.published?
  #     @testimonial.testimonial_request.destroy
  #   end
  #   redirect_to testimonials_path,
  #               notice: "Testimonial was #{'un' unless @testimonial.published? }published"
  # end

  def approve
    @review.update_attributes :approved => true

    redirect_to reviews_path, :notice => "Review was approved"
  end

  protected

  def set_review
    @review = current_user.reviews.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:image, :name, :role, :company, :content, :title, :rating)
  end
end

app/controllers/backend/templates_controller.rb
class Backend::TemplatesController < Backend::ApplicationController
  #inherit_resources
  #actions :show
  #respond_to :json
end

app/controllers/backend/testimonials_controller.rb
class Backend::TestimonialsController < ApplicationController
  before_action :set_testimonial, except: [:index, :new, :create]

  def index
    @testimonials = current_user.testimonials.order('created_at DESC')
  end

  def new
    @testimonial = Testimonial.new
    @templates = TestimonialTemplate.all
    @request =
      Request.new :sender => current_user.name, :reply_to => current_user.email
  end

  def create
    @testimonial = current_user.testimonials.new(testimonial_params)

    if @testimonial.save
      redirect_to testimonials_path, notice: 'Testimonial created'
    else
      @templates = TestimonialTemplate.all
      @request =
        Request.new :sender => current_user.name, :reply_to => current_user.email
      render :new
    end
  end

  def edit
    @testimonial = Testimonial.find params[:id]
    @templates = TestimonialTemplate.all
  end

  def update
    if @testimonial.update(testimonial_params)
      redirect_to testimonials_path, notice: 'Testimonial updated'
    else
      render :edit
    end
  end

  def destroy
    redirect_to testimonials_path, notice: 'Testimonial destroyed' if @testimonial.destroy
  end

  def publish
    @testimonial.toggle(:published).save
    if @testimonial.testimonial_request && @testimonial.published?
      @testimonial.testimonial_request.destroy
    end
    redirect_to testimonials_path,
                notice: "Testimonial was #{'un' unless @testimonial.published? }published"
  end

  def approve
    @testimonial.update_attributes :approved => true

    redirect_to testimonials_path, :notice => "Testimonial was approved"
  end

  protected

  def set_testimonial
    @testimonial = current_user.testimonials.find(params[:id])
  end

  def testimonial_params
    params.require(:testimonial).permit(:image, :name, :role, :company, :content, :template_id)
  end
end

app/controllers/frontend/case_studies_controller.rb
class Frontend::CaseStudiesController < Frontend::ApplicationController
  #inherit_resources
  #actions :index, :show
  #resources_configuration[:self][:finder] = :find_by_url!
  #belongs_to :user, finder: :find_by_url!, param: :user_url
  #has_scope :page, default: 1
  #respond_to :html, :json

  before_filter :check_referer, only: [:code]
  skip_before_filter :verify_authenticity_token, only: [:tile]

  def show
    user = User.find_by_url!(params[:user_url])
    @case_study = user.case_studies.find_by_url!(params[:url])
  end

  def index
    @user = User.find_by_url!(params[:user_url])
    @case_studies = @user.case_studies.where(step: 'published')
  end

  # usefull in case of subdomains
=begin
  def show
    @user = if params[:by_domain]
              User.find_by_domain(request.subdomain)
            else
              User.find_by_url(params[:user_url])
            end
    @case_study = @user.case_studies.find_by_url(params[:url])
  end
=end

  def tile
    @case_study = CaseStudy.find(params[:id])

    respond_to do |format|
      format.json { render json: { html: @case_study.tile_template_compiled.html_safe } }
    end
  end

  # TODO now it's here, but need to think how to structure 'frontend' controllers better
  def testimonial
    @testimonial = Testimonial.find(params[:id])

    respond_to do |format|
      format.json { render json: { html: @testimonial.template_with_pic.html_safe } }
    end
  end

  def code
    html = collection.per(3).pluck(:tile_template_compiled).join
    render layout: false, text: html
  end

  protected
  def resource
    get_resource_ivar || set_resource_ivar(end_of_association_chain.send(method_for_find, params[:url]))
  end

  def validate_request
    u = URI(request.referer)
    u.query = u.fragment = nil
    u.path = ''
    SignUtils.sign(u.host) == params[:sign] && parent.domain == u.host rescue false
  end

  def check_referer
    return unless request.referer
    response.headers['Access-Control-Allow-Origin'] = URI.join(request.referer, '/').to_s[0..-2] if validate_request
  end

  def premailer_params
    {
      warn_level: Premailer::Warnings::NONE,
      with_html_string: true,
      remove_ids: true,
      remove_comments: true,
      include_link_tags: false,
      preserve_styles: false
    }
  end
end

app/views/backend/case_studies/content.haml
%section.body-campaign
  .wrap-two
    .row
      .col-lg-4.col-md-4.col-sm-4.col-xs-12.pull-left
        %h1.step1
          Create content of case study
          %span#campaignName
            = @case_study.title
      .col-lg-4.col-md-4.col-sm-4.col-xs-12
        .tests
          %ul.campaigns-menu.two.nav.navbar-nav.pull-right
            %li#regular-tab.current
              %a.text{:href => ""}
                %i.fa.fa-envelope-o
                Regular
            %li#absplit-tab
              %a.text{:href => ""}
                %i.fa.fa-users
                A/B test
      .col-lg-4.col-md-4.col-sm-4.col-xs-12
        .camp-prog.pull-right
          %div{:style => "display: block"}
            = image_tag('campaign.png')
          #sfIcons.camp-prog-sf1{:style => "display: none"}
          #coIcons.camp-prog-co1{:style => "display:none"}
          #trIcons.camp-prog-tr1{:style => "display: none"}
/ Body section Input
%section.body-campaign-input
  .wrap-three.container-fluid
    .row
      .col-lg-12.col-md-12.col-xs-12.col-sm-12
        #regular
          #campaign-editor
            = form_for @case_study do
              = hidden_field_tag :step, :content
              #regular-content{:style => ""}
                %ul.primary-form{ style: 'width: 80%;'}
                  %li
                    .box-wrap
                      = text_area_tag :template_content, @case_study.template_content,
                      data: {provider: :summernote}, name: 'case_study[template_content]',
                      id: 'case_study_template_content'
              .primary-form.padding-none
                #submit-wrap.button-cancel.wizard{:style => ""}
                  %button#submitButton.button.primary.huge.forward
                    Next
                    %i.fa.fa-arrow-right

app/views/backend/case_studies/index.haml
%section.body-section
  .wrap-two.container-fluid
    .row
      .col-lg-10.col-md-9.col-sm-12.col-xs-12
        .table-responsive.leftcol
          %h1
            Case studies
            //%span.extras
            //  %a{:href => ''} See all saved drafts
          %table#drafts.table-hover{:cellpadding => '0', :cellspacing => '0'}
            %tbody
              %tr.noHighlight
                %th.headerLeft{:style => 'width: 61%;'} Case study
                %th{:style => 'width: 18.5%;'} Created
                %th.cellCenter{:style => 'width: 7%;'} Ready
                %th.cellCenter{:style => 'width: 7%;'} Published
                %th.headerRight{:style => 'width: 5.5%;'}
              - @case_studies.each do |case_study|
                %tr.hover-toggle
                  %td
                    - if case_study.ready?
                      = link_to case_study, case_study_path(case_study), class: 'left'
                    - else
                      = link_to case_study, edit_case_study_path(case_study), class: 'left'
                    %br/
                    .clearit
                  %td
                    = case_study.created_at.to_formatted_s(:long)
                  %td.cellCenter
                    - if case_study.ready?
                      = image_tag 'tick.png', alt: 'Yes'
                    - else
                      = image_tag 'minus.png', alt: 'No'
                  %td.cellCenter
                    - if case_study.ready?
                      = link_to publish_case_study_path(case_study), method: :post,
                                data: {confirm: "Do you want to #{'un' if case_study.published?}publish case study?" } do
                        - if case_study.published?
                          = image_tag 'tick.png', alt: 'Yes'
                        - else
                          = image_tag 'minus.png', alt: 'No'
                    - else
                      = image_tag 'minus.png', alt: 'No'
                  %td.cellCenter
                    = link_to case_study, method: :delete,
                              data: { confirm: 'Do you want to delete case study?' } do
                      %span.glyphicon.glyphicon-remove
      .col-lg-2.col-md-3.col-sm-12.col-xs-12
        = render 'layouts/right_bar'

app/views/backend/case_studies/logo.haml
%section.body-campaign
  .wrap-two
    .row
      .col-lg-4.col-md-4.col-sm-4.col-xs-12.pull-left
        %h1.step1
          Define the case study and client details
          %span#campaignName Choose from two campaign types
      .col-lg-4.col-md-4.col-sm-4.col-xs-12
        .tests
          %ul.campaigns-menu.two.nav.navbar-nav.pull-right
            %li#regular-tab.current
              %a.text{:href => ""}
                %i.fa.fa-envelope-o
                Regular
            %li#absplit-tab
              %a.text{:href => ""}
                %i.fa.fa-users
                A/B test
      .col-lg-4.col-md-4.col-sm-4.col-xs-12
        .camp-prog.pull-right
          %div{:style => "display: block"}
            = image_tag('campaign.png')
          #sfIcons.camp-prog-sf1{:style => "display: none"}
          #coIcons.camp-prog-co1{:style => "display:none"}
          #trIcons.camp-prog-tr1{:style => "display: none"}
/ Body section Input
%section.body-campaign-input
  .wrap-three.container-fluid
    .row
      .col-lg-12.col-md-12.col-xs-12.col-sm-12
        #regular
          #campaign-editor
            = simple_form_for @case_study do |f|
              #regular-content{:style => ""}
                %ul.primary-form
                  %li
                    %label Upload client's logo or photo
                    .helper-text This will be used in case study construction
                    .box-wrap
                      = f.input :image, wrapper: 'testify'
                      .image{style: 'width: 200px;'}
                        = image_tag(@case_study.image.url) if @case_study.image?
                    = hidden_field_tag :step, :logo
                    = f.submit 'Next', class: 'hidden'
              .primary-form.padding-none
                #submit-wrap.button-cancel.wizard{:style => ""}
                  %button#submitButton.button.primary.huge.forward
                    Next
                    %i.fa.fa-arrow-right

app/views/backend/case_studies/new.haml
%section.body-campaign
  .wrap-two
    .row
      .col-lg-4.col-md-4.col-sm-4.col-xs-12.pull-left
        %h1.step1 Define the case study and client details
        %span#campaignName Choose from two campaign types
      .col-lg-4.col-md-4.col-sm-4.col-xs-12.tests-container
        .tests
          #request-review-button.request-write-button
            %i.fa.fa-envelope-o
            %span General
          #new-review-button.request-write-button
            %i.fa.fa-users
            %span White Label
      .col-lg-4.col-md-4.col-sm-4.col-xs-12
        .camp-prog.pull-right
          %div{:style => "display: block"}
            = image_tag('campaign.png')
          #sfIcons.camp-prog-sf1{:style => "display: none"}
          #coIcons.camp-prog-co1{:style => "display:none"}
          #trIcons.camp-prog-tr1{:style => "display: none"}
/ Body section Input
%section.body-campaign-input
  .wrap-three.container-fluid
    .row
      .col-lg-12.col-md-12.col-xs-12.col-sm-12
        #regular
          #campaign-editor
            = simple_form_for @case_study do |f|
              = hidden_field_tag :step, :main
              #regular-content{:style => ""}
                %ul.primary-form
                  %li
                    %label Name this case study
                    .helper-text This is a case study title
                    .box-wrap
                      = f.input :title, autofocus: 'autofocus', wrapper: 'testify',
                                       class: 'title-field width-full first'
                  %li#regSubject{:style => ""}
                    %label Write a client's name
                    .helper-text
                      This will be used in case study construction
                    .box-wrap
                      = f.input :client, class: 'clientname-field width-full first', wrapper: 'testify'
                    = f.submit 'Next', class: 'hidden'
              .primary-form.padding-none
                #submit-wrap.button-cancel.wizard{:style => ""}
                  %button#submitButton.button.primary.huge.forward
                    Next
                    %i.fa.fa-arrow-right

app/views/backend/case_studies/show.haml
%section.body-campaign
  .wrap-two
    .row
      .col-lg-4.col-md-4.col-sm-4.col-xs-12.pull-left
        %h1.step1
          = @case_study.client
          %span#campaignName
            = @case_study.title
      .col-lg-4.col-md-4.col-sm-4.col-xs-12
      .col-lg-4.col-md-4.col-sm-4.col-xs-12
        .buttons.pull-right{style: 'margin: 10px;'}
          = link_to 'preview', public_case_study_path(@case_study.user.url, @case_study.url),
                  class: 'btn btn-primary', style: 'margin-top: 10px;'
          %br
          = link_to 'edit', edit_case_study_path(@case_study), class: 'btn btn-primary',
                    style: 'margin-top: 10px;'
        .camp-prog.pull-right
          #sfIcons.camp-prog-sf1{:style => "display: none"}
          #coIcons.camp-prog-co1{:style => "display:none"}
          #trIcons.camp-prog-tr1{:style => "display: none"}
/ Body section Input
%section.body-campaign-input
  .wrap-three.container-fluid
    .row
      .col-lg-6.col-md-6.col-xs-6.col-sm-6
        #regular
          #campaign-editor
            #regular-content{:style => ""}
              %ul.primary-form{style: 'width: auto;'}
                %li
                  %label Tile preview
                  = link_to public_case_study_path(@case_study.user.url, @case_study.url) do
                    = render html: @case_study.tile_template_content.html_safe
      .col-lg-6.col-md-6.col-xs-6.col-sm-6
        #regular
          #campaign-editor
            #regular-content{:style => ""}
              %ul.primary-form{style: 'width: auto;'}
                %li
                  %label Tile code
                  .helper-text Copy this code to your page to embed case stidy tile
                  .box-wrap.tile-code
                    = text_area_tag :tile_code, @case_study.tile_code,
                                    style: 'width: 100%; height: 120px;'
                    = link_to 'Copy to clipboard', '#', class: 'btn btn-primary',
                              id: 'tileToClipboard', style: 'margin: 5px;'

app/views/backend/case_studies/template.haml
%section.body-campaign
  .wrap-two
    .row
      .col-lg-6.col-md-6.col-sm-6.col-xs-9.pull-left
        %h1.step1
          Choose a template to get started
          %span#campaignName
            = @case_study.title
      .col-lg-6.col-md-6.col-sm-6.col-xs-12.pull-right
        .camp-prog.pull-right
          %div{:style => "display: block"}
            = image_tag('campaign.png')
            #sfIcons.camp-prog-sf1{:style => "display: none"}
            #coIcons.camp-prog-co1{:style => "display:none"}
            #trIcons.camp-prog-tr1{:style => "display: none"}
  / Body section Input
  %section.body-campaign-input
    .wrap-three.container-fluid
      .row
        .col-lg-2.col-md-4.col-xs-9.col-sm-4
          .template-sidebar.pull-right
            .template-sidebar-single
              %h2 Ready to go
              %ul
                %li
                  %a{:href => ""} Recent Email
                %li
                  %a{:href => ""} My Templates
            .template-sidebar-single
              %h2 Create new
              %ul
                %li
                  %a{:href => ""} Featured
                %li
                  %a{:href => ""} Announcements
                %li
                  %a{:href => ""} Newsletters
                %li
                  %a{:href => ""} Deals  offers
                %li
                  %a{:href => ""} Events
                %li
                  %a{:href => ""} Transactional
            .template-sidebar-single
              %h2 More options
              %ul
                %li
                  %a{:href => ""} Import HTML
                %li
                  %a{:href => ""} Plain text
        .col-lg-10.col-md-8.col-sm-8.col-xs-12
          .sidebar-right
            %ul.nav.navbar-nav
              - CaseStudyTemplate.all.each do |template|
                %li.list-item.col-lg-4
                  %figure
                    .single-list-item
                      = link_to '#', class: 'single-link template-link' do
                        = form_for @case_study do |f|
                          = hidden_field_tag 'case_study[template_id]', template.id
                          = hidden_field_tag :step, :template
                          = f.submit 'Next', class: 'hidden'
                        .img-thumbnail__status-pill Draft
                        .single-img
                          = image_tag template.preview.url, alt: template.title
                      %figcaption.js-flip-face.c-flip-3d__face.c-flip-3d__face--front.img-thumbnail__link.qa-link-select-previously-sent-A7E60C50E008E9D5
                        %time.img-thumbnail__date
                          = template.updated_at.to_date.to_formatted_s(:short)
                        %abbr.img-thumbnail__name{ title: template.title }
                          = template.title

app/views/backend/case_studies/tile_content.haml
tile content
= link_to 'finish', '#'

app/views/backend/case_studies/tile_template.haml
tile template
= link_to 'next', new_case_study_path(step: :tile_content)