config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
                     sessions: 'users/sessions',
                     registrations: 'users/registrations',
                     confirmations: 'users/confirmations',
                     passwords: 'users/passwords',
                     unlocks: 'users/unlocks',
                     omniauth_callbacks: 'users/omniauth_callbacks'
                   }

  # Subdomains are currently not available on heroku
  #constraints(subdomain: /.+/) do
    #get '/:url', to: 'frontend/case_studies#show', by_domain: true
    #get '*path' => redirect('/')
  #end

  # For redirect after sign in
  get 'case_studies' => 'backend/case_studies#index', as: :user_root

  concern :publishable do
    post :publish, on: :member
  end

  concern :approvable do
    post :approve, on: :member
  end

  resources :case_studies, controller: 'backend/case_studies',
            path_names: { edit: 'edit(/:step)' },
            concerns: :publishable do
    #collection do
    #  post :add_image, :add_template
    #end
  end

  resources :testimonials, controller: 'backend/testimonials',
            :concerns => [:publishable, :approvable]

  resources :reviews, controller: 'backend/reviews',
            :concerns => [:publishable, :approvable]

  resources :requests, controller: 'backend/requests', :only => [:index, :destroy]

  match '/requests/new_testimonial' => 'backend/requests#new_testimonial',
    :via => :get, :as => :new_testimonial_request
  match '/requests/create_testimonial' => 'backend/requests#create_testimonial',
    :via => :post, :as => :create_testimonial_request

  match '/requests/new_review' => 'backend/requests#new_review',
    :via => :get, :as => :new_review_request
  match '/requests/create_review' => 'backend/requests#create_review',
    :via => :post, :as => :create_review_request

  match '/testimonial/request/new/:token' => 'backend/requests#new_customer_testimonial',
    :via => :get, :as => :new_customer_testimonial
  match '/testimonial/request/:token' => 'backend/requests#create_customer_testimonial',
    :via => :post, :as => :create_customer_testimonial

  match '/review/request/new/:token' => 'backend/requests#new_customer_review',
    :via => :get, :as => :new_customer_review
  match '/review/request/:token' => 'backend/requests#create_customer_review',
    :via => :post, :as => :create_customer_review

  resources :templates, controller: 'backend/templates'

  # embedding routes
  match '/render_tile/:id' => 'frontend/case_studies#tile', via: [:get, :options]
  match '/render_testimonial/:id' => 'frontend/case_studies#testimonial', via: [:get, :options]

  get ':user_url' => 'frontend/case_studies#index', as: :public_case_studies
  get ':user_url/code' => 'frontend/case_studies#code', as: :code_case_studies
  get ':user_url/:url' => 'frontend/case_studies#show', as: :public_case_study

  root 'backend/home#index'
end

app/controllers/backend/application_controller.rb
module Backend
  class ApplicationController < ::ApplicationController
    before_filter :authenticate_user!
  end
end

app/controllers/backend/case_studies_controller.rb
class Backend::CaseStudiesController < Backend::ApplicationController
  #include Wicked::Wizard
  before_action :set_case_study, except: [:index, :new, :create]
  #steps :template, :content, :tile_template, :tile_content

  def index
    @case_studies = current_user.case_studies.all
  end

  def new
    @case_study = CaseStudy.new
  end

  def main
    wizard_save(nil, next: :logo, back: :edit)
  end

  def logo
    @case_study.update(case_study_params) if case_study_params
    wizard_save(:validate_logo, next: :template, back: :logo)
  end

  def template
    if case_study_params[:template_id]
      @case_study.insert_template CaseStudyTemplate
                                      .find(case_study_params[:template_id]).template
    end
    wizard_save(:validate_template, next: :content, back: :template)
  end

  def content
    @case_study.update(case_study_params) if case_study_params
    #wizard_save(:validate_template, next: :tile_template, back: :content)
    @case_study.next_step
    @case_study.insert_tile TileTemplate.take.template # temp we have one tile template
    redirect_to case_study_path(@case_study), notice: 'Case study created!'
  end

  def tile_template
    # TBD
  end

  def tile_content
    # TBD
  end

  def create
    @case_study = current_user.case_studies.new(case_study_params)
    wizard_save(nil, next: :logo, back: :new)
  end

  def show
    redirect_to case_studies_path, alert: 'Case study is not finished' unless @case_study.ready?
  end

  def edit
    params[:step] ||= @case_study.ready? ? :content : @case_study.step
    render params[:step]
  end

  def update
    send(params[:step]) if params[:step].present?
  end

  def destroy
    redirect_to case_studies_path, notice: 'Case study destroyed' if @case_study.destroy
  end

  #def add_template
  #  template = Nokogiri::HTML(params[:template].read)
  #  template.css('script,iframe').remove
  #  @template = template.to_s
  #  @editor_index =  %w(case_study tile).find_index(params[:type])
  #  respond_to :js
  #end

  def publish
    @case_study.toggle_published
    redirect_to case_studies_path,
                notice: "Case study was #{'un' unless @case_study.published? }published"
  end

  protected

  def set_case_study
    @case_study = CaseStudy.find(params[:id])
  end

  def case_study_params
    if params[:case_study].present? && params[:case_study].any?
      params.require(:case_study).permit(:image, :client, :title, :template_id,
                                         :template_content, :tile_template_content)
    end
  end

  def wizard_save(validation, args = {})
    if (validation ? send(validation, @case_study) : true) && @case_study.save
      @case_study.next_step
      redirect_to edit_case_study_path(@case_study, step: args[:next])
    else
      render args[:back]
    end
  end

  private

  def validate_logo(cs)
    cs.errors[:image] << 'should be uploaded' unless cs.image.present?
    cs.errors.empty?
  end

  def validate_template(cs)
    cs.errors[:template_content] << 'should be choosen' unless cs.template_content.present?
    cs.errors.empty?
  end

end

app/controllers/backend/home_controller.rb
class Backend::HomeController < ApplicationController
  def index
    # overview page
  end
end

app/controllers/backend/requests_controller.rb
class Backend::RequestsController < ApplicationController
  #has_scope :page, default: 1
  before_action :init_request, :only => [:new_testimonial, :new_review]



  def create_testimonial
    @request = current_user.requests.new(request_params)
    @request.request_type = :testimonial

    if @request.save
      @request.send_mail
      redirect_to requests_path, :notice => 'Request for Testimonial sent'
    else
      @testimonial = Testimonial.new
      @templates = TestimonialTemplate.all
      render 'backend/testimonials/new'
    end
  end

  def create_review
    @request = current_user.requests.new(request_params)
    @request.request_type = :review

    if @request.save
      @request.send_mail
      redirect_to requests_path, :notice => 'Request for Review sent'
    else
      @review = Review.new
      render 'backend/reviews/new'
    end
  end

  def index
    @requests = current_user.requests.order('created_at DESC')
  end

  def destroy
    @request = current_user.requests.find params[:id]
    redirect_to requests_path, notice: 'Request destroyed' if @request.destroy
  end

  def new_customer_testimonial
    @request = Request.find_by_token params[:token]
    if @request && @request.status == 'sent'
      @testimonial =
        Testimonial.new :name => @request.name, :request_token => params[:token]
      @templates = TestimonialTemplate.all
    else
      redirect_to testimonials_path, :notice => 'Testimonial created'
    end
  end

  def new_customer_review
    @request = Request.find_by_token params[:token]
    if @request && @request.status == 'sent'
      @review =
        Review.new :name => @request.name, :request_token => params[:token]
    else
      redirect_to reviews_path, :notice => 'Review created'
    end
  end

  def create_customer_testimonial
    @request = Request.find_by_token params[:token]
    @user = @request.user
    @testimonial = @user.testimonials.new(testimonial_params)

    if @testimonial.save
      # @request.testimonial = @testimonial
      @request.update_attributes :status => 'Filled by customer'
      redirect_to testimonials_path, :notice => 'Thank you for your feedback!' # later thanks page
    else
      @templates = TestimonialTemplate.all
      render :new_customer_testimonial
    end
  end

  def create_customer_review
    @request = Request.find_by_token params[:token]
    @user = @request.user
    @review = @user.reviews.new(review_params)

    if @review.save
      # @request.review = @review
      @request.update_attributes :status => 'Filled by customer'
      redirect_to reviews_path, :notice => 'Thank you for your feedback!' # later thanks page
    else
      render :new_customer_review
    end
  end

  private

  def init_request
    @request =
      Request.new :sender => current_user.name, :reply_to => current_user.email
  end

  def testimonial_params
    params.require(:testimonial).permit(:image, :name, :role, :company, :content, :template_id)
  end

  def review_params
    params.require(:review).permit(:image, :name, :role, :company, :content, :title, :rating)
  end

  def request_params
    params.require(:request).
      permit(:name, :email, :sender, :reply_to, :subject, :message)
  end

end

app/controllers/backend/reviews_controller.rb
class Backend::ReviewsController < ApplicationController
  before_action :set_review, except: [:index, :new, :create]

  def index
    @reviews = current_user.reviews.order('created_at DESC')
  end

  def new
    @review = Review.new
    @request =
      Request.new :sender => current_user.name, :reply_to => current_user.email
  end

  def create
    @review = current_user.reviews.new(review_params)

    if @review.save
      redirect_to reviews_path, :notice => 'Review created'
    else
      @request =
        Request.new :sender => current_user.name, :reply_to => current_user.email
      render :new
    end
  end

  def edit
    @review = Review.find params[:id]
  end

  def update
    if @review.update(review_params)
      redirect_to reviews_path, :notice => 'Review updated'
    else
      render :edit
    end
  end

  def destroy
    if @review.destroy
      redirect_to reviews_path, :notice => 'Review destroyed'
    end
  end

  # def publish
  #   @testimonial.toggle(:published).save
  #   if @testimonial.testimonial_request && @testimonial.published?
  #     @testimonial.testimonial_request.destroy
  #   end
  #   redirect_to testimonials_path,
  #               notice: "Testimonial was #{'un' unless @testimonial.published? }published"
  # end

  def approve
    @review.update_attributes :approved => true

    redirect_to reviews_path, :notice => "Review was approved"
  end

  protected

  def set_review
    @review = current_user.reviews.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:image, :name, :role, :company, :content, :title, :rating)
  end
end

app/controllers/backend/templates_controller.rb
class Backend::TemplatesController < Backend::ApplicationController
  #inherit_resources
  #actions :show
  #respond_to :json
end

app/controllers/backend/testimonials_controller.rb
class Backend::TestimonialsController < ApplicationController
  before_action :set_testimonial, except: [:index, :new, :create]

  def index
    @testimonials = current_user.testimonials.order('created_at DESC')
  end

  def new
    @testimonial = Testimonial.new
    @templates = TestimonialTemplate.all
    @request =
      Request.new :sender => current_user.name, :reply_to => current_user.email
  end

  def create
    @testimonial = current_user.testimonials.new(testimonial_params)

    if @testimonial.save
      redirect_to testimonials_path, notice: 'Testimonial created'
    else
      @templates = TestimonialTemplate.all
      @request =
        Request.new :sender => current_user.name, :reply_to => current_user.email
      render :new
    end
  end

  def edit
    @testimonial = Testimonial.find params[:id]
    @templates = TestimonialTemplate.all
  end

  def update
    if @testimonial.update(testimonial_params)
      redirect_to testimonials_path, notice: 'Testimonial updated'
    else
      render :edit
    end
  end

  def destroy
    redirect_to testimonials_path, notice: 'Testimonial destroyed' if @testimonial.destroy
  end

  def publish
    @testimonial.toggle(:published).save
    if @testimonial.testimonial_request && @testimonial.published?
      @testimonial.testimonial_request.destroy
    end
    redirect_to testimonials_path,
                notice: "Testimonial was #{'un' unless @testimonial.published? }published"
  end

  def approve
    @testimonial.update_attributes :approved => true

    redirect_to testimonials_path, :notice => "Testimonial was approved"
  end

  protected

  def set_testimonial
    @testimonial = current_user.testimonials.find(params[:id])
  end

  def testimonial_params
    params.require(:testimonial).permit(:image, :name, :role, :company, :content, :template_id)
  end
end

app/views/backend/reviews/_ratings.haml
= fa_icon "star-o", :class => 'review-rating-stars', :data => {:rating => 1}
= fa_icon "star-o", :class => 'review-rating-stars', :data => {:rating => 2}
= fa_icon "star-o", :class => 'review-rating-stars', :data => {:rating => 3}
= fa_icon "star-o", :class => 'review-rating-stars', :data => {:rating => 4}
= fa_icon "star-o", :class => 'review-rating-stars', :data => {:rating => 5}

app/views/backend/reviews/edit.haml
%section.body-campaign
  .wrap-two
    .row
      .col-lg-4.col-md-4.col-sm-4.col-xs-12.pull-left
        %h1.step1
          Edit review
          %span#campaignName Fill necessary fields
      .col-lg-4.col-md-4.col-sm-4.col-xs-12
      .col-lg-4.col-md-4.col-sm-4.col-xs-12
        .camp-prog.pull-right
          %div{:style => "display: block"}
            = image_tag('campaign.png')
          #sfIcons.camp-prog-sf1{:style => "display: none"}
          #coIcons.camp-prog-co1{:style => "display: none"}
          #trIcons.camp-prog-tr1{:style => "display: none"}
/ Body section Input
%section.body-campaign-input
  .wrap-three.container-fluid
    .row
      .col-lg-12.col-xs-12.col-sm-8
        #regular
          #campaign-editor
            = simple_form_for @review do |f|
              #regular-content{:style => ""}
                %ul.primary-form
                  %li
                    %label Write review by myself
                    .helper-text
                      You can write review, also you can request it from your client
                    .box-wrap
                      = render 'ratings'
                    .box-wrap
                      = f.input :title, autofocus: 'autofocus', placeholder: "Title",
                                       class: 'title-field width-full first', wrapper: 'testify'
                    .box-wrap
                      = f.input :name, placeholder: "Client's name",
                                       class: 'title-field width-full first', wrapper: 'testify'
                    .box-wrap
                      = f.input :image, wrapper: 'testify'
                      .image{style: 'width: 200px;'}
                        = image_tag(@review.image.url) if @review.image?
                    .box-wrap
                      = f.input :role, placeholder: "Client's role in company",
                                       class: 'title-field width-full first', wrapper: 'testify'
                    .box-wrap
                      = f.input :company, placeholder: "Company",
                                       class: 'title-field width-full first', wrapper: 'testify'
                    .box-wrap
                      = f.input :content, class: 'clientname-field width-full first', wrapper: 'testify',
                                    style: 'resize: none; height: 150px;', placeholder: 'Review'
                      = f.input :rating, :as => :hidden, :input_html => {:class => 'review-rating-field'}
                      = hidden_field_tag 'review-rating', @review.rating

                    = f.submit 'Next', class: 'hidden'
              .primary-form.padding-none
                #submit-wrap.button-cancel.wizard{:style => ""}
                  %button#submitButton.button.primary.huge.forward
                    Update

app/views/backend/reviews/index.haml
%section.body-section
  .wrap-two.container-fluid
    .row
      .col-lg-10.col-md-9.col-sm-12.col-xs-12
        .table-responsive.leftcol
          %h1
            Reviews
          %table#drafts.table-hover{:cellpadding => '0', :cellspacing => '0'}
            %tbody
              %tr.noHighlight
                %th.headerLeft{:style => 'width: 40%;'} Review
                %th.cellCenter{:style => 'width: 18.5%;'} Rating
                %th{:style => 'width: 18.5%;'} Created
                %th.cellCenter{:style => 'width: 7%;'} Ready
                %th.cellCenter{:style => 'width: 7%;'} Approved
                %th.headerRight{:style => 'width: 10%;'}
              - @reviews.each do |review|
                %tr.hover-toggle
                  %td
                    = link_to review, review_path(review), class: 'row-left'
                    %br/
                    .clearit
                  %td.cellCenter
                    = review.rating
                  %td
                    = review.created_at.to_formatted_s(:long)
                  %td.cellCenter
                    = image_tag 'tick.png', alt: 'Yes'
                  %td.cellCenter
                    / = link_to publish_review_path(review), method: :post,
                    /           data: {confirm: "Do you want to #{'un' if review.published?}publish review?" } do
                    - if review.approved?
                      = image_tag 'tick.png', alt: 'Yes'
                    - else
                      = image_tag 'minus.png', alt: 'No'
                  %td.cellCenter
                    = link_to review, method: :delete,
                              data: { confirm: 'Do you want to delete review?' } do
                      %span.glyphicon.glyphicon-remove
      .col-lg-2.col-md-3.col-sm-12.col-xs-12
        = render 'layouts/right_bar'

app/views/backend/reviews/new.haml
%section.body-campaign
  .wrap-two
    .row
      .col-lg-4.col-md-4.col-sm-4.col-xs-12.pull-left
        %h1.step1 New review
        %span#campaignName Fill necessary fields
      .col-lg-4.col-md-4.col-sm-4.col-xs-12.tests-container
        .tests
          #request-review-button.request-write-button
            %i.fa.fa-envelope-o
            %span Review
          #new-review-button.request-write-button
            %i.fa.fa-users
            %span Write Myself
      .col-lg-4.col-md-4.col-sm-4.col-xs-12
        .camp-prog.pull-right
          %div{:style => "display: block"}
            = image_tag('campaign.png')
          #sfIcons.camp-prog-sf1{:style => "display: none"}
          #coIcons.camp-prog-co1{:style => "display: none"}
          #trIcons.camp-prog-tr1{:style => "display: none"}
/ Body section Input
%section#new-review-form.body-campaign-input
  .wrap-three.container-fluid
    .row
      .col-lg-12.col-xs-12.col-sm-8
        #regular
          #campaign-editor
            = simple_form_for @review do |f|
              #regular-content{:style => ""}
                %ul.primary-form
                  %li
                    %label Write review by myself
                    .helper-text
                      You can write review, also you can request it from your client
                    .box-wrap
                      = render 'backend/reviews/ratings'
                    .box-wrap
                      = f.input :title, autofocus: 'autofocus', placeholder: "Title",
                                       class: 'title-field width-full first', wrapper: 'testify'
                    .box-wrap
                      = f.input :name, placeholder: "Client's name",
                                       class: 'title-field width-full first', wrapper: 'testify'
                    .box-wrap
                      = f.input :image, wrapper: 'testify'
                      .image{style: 'width: 200px;'}
                        = image_tag(@review.image.url) if @review.image?
                    .box-wrap
                      = f.input :role, placeholder: "Client's role in company",
                                       class: 'title-field width-full first', wrapper: 'testify'
                    .box-wrap
                      = f.input :company, placeholder: "Company",
                                       class: 'title-field width-full first', wrapper: 'testify'
                    .box-wrap
                      = f.input :content, class: 'clientname-field width-full first', wrapper: 'testify',
                                    style: 'resize: none; height: 150px;', placeholder: 'Review'
                      = f.input :rating, :as => :hidden, :input_html => {:class => 'review-rating-field'}
                      = hidden_field_tag 'review-rating', 0

                    = f.submit 'Next', class: 'hidden'
              .primary-form.padding-none
                #submit-wrap.button-cancel.wizard{:style => ""}
                  %button#submitButton.button.primary.huge.forward
                    Create

%section#request-review-form.body-campaign-input
  .wrap-three.container-fluid
    .row
      .col-lg-12.col-xs-12.col-sm-8
        #regular
          #campaign-editor
            = simple_form_for @request, :url => create_review_request_path do |f|
              #regular-content{:style => ""}
                %ul.primary-form
                  %li
                    %label Sender info
                    .helper-text This is your details as sender
                    .box-wrap
                      = f.input :sender, placeholder: "Sender's name",
                                       class: 'title-field width-full first', wrapper: 'testify'
                    .box-wrap
                      = f.input :reply_to, placeholder: 'reply to address',
                                       class: 'title-field width-full first', wrapper: 'testify'
                  %li#regSubject{:style => ""}
                    %label Recipient info
                    .helper-text
                      This is your customer's details
                    .box-wrap
                      = f.input :name, autofocus: 'autofocus', placeholder: "Recipient's name",
                                     class: 'clientname-field width-full first', wrapper: 'testify'
                    .box-wrap
                      = f.input :email, placeholder: "Recipient's email",
                                     class: 'clientname-field width-full first', wrapper: 'testify'
                  %li#regSubject{:style => ""}
                    %label Request info
                    .helper-text
                      This is your request for review details
                    .box-wrap
                      = f.input :subject, placeholder: 'Email subject',
                                     class: 'clientname-field width-full first', wrapper: 'testify'
                    .box-wrap
                      = f.input :message, placeholder: 'Request message',
                                     class: 'clientname-field width-full first', wrapper: 'testify'
                    = f.submit 'Next', class: 'hidden'
              .primary-form.padding-none
                #submit-wrap.button-cancel.wizard{:style => ""}
                  %button#submitButton.button.primary.huge.forward
                    Send
                    %i.fa.fa-arrow-right

app/views/backend/reviews/show.haml
%section.body-campaign
  .wrap-two
    .row
      .col-lg-4.col-md-4.col-sm-4.col-xs-12.pull-left
        %h1.step1
          = @review.name
          %span#campaignName
            = @review.company
      .col-lg-4.col-md-4.col-sm-4.col-xs-12
      .col-lg-4.col-md-4.col-sm-4.col-xs-12
        .buttons.pull-right{style: 'margin: 10px; padding-top: 20px;'}
          = link_to 'Approve', approve_review_path(@review), :method => :post, :class => 'btn btn-primary'
          / = link_to 'Edit', edit_review_path(@review), :class => 'btn btn-primary'
          = link_to 'Delete', @review, :method => :delete,
            :data => { :confirm => 'Do you want to delete Review?' },
            :class => 'btn btn-danger'
        .camp-prog.pull-right
          #sfIcons.camp-prog-sf1{:style => "display: none"}
          #coIcons.camp-prog-co1{:style => "display:none"}
          #trIcons.camp-prog-tr1{:style => "display: none"}
/ Body section Input
%section.body-campaign-input
  .wrap-three.container-fluid
    .row
      .col-lg-6.col-md-6.col-xs-6.col-sm-6
        #regular
          #campaign-editor
            #regular-content{:style => ""}
              %ul.primary-form{style: 'width: auto;'}
                %li
                  %label Review preview
                  / = render html: @review.template_with_pic.html_safe
                  .review-preview-container
                    .review-header-container
                      .review-rating-container
                        = hidden_field_tag 'review-rating', @review.rating
                        = render 'ratings'
                      .review-title
                        = @review.title
                    .review-content
                      = @review.content
                    .review-creator-container
                      .review-creator-image-container
                        - if @review.image.file?
                          = image_tag @review.image.url
                        - else
                          = image_tag 'default.jpg'
                      .review-creator-details
                        = @review
      .col-lg-6.col-md-6.col-xs-6.col-sm-6
        #regular
          #campaign-editor
            #regular-content{:style => ""}
              %ul.primary-form{style: 'width: auto;'}
                %li
                  %label Review code
                  .helper-text Copy this code to your page to embed review
                  .box-wrap.tile-code
                    = text_area_tag :tile_code, @review.review_code,
                                    style: 'width: 100%; height: 120px;'
                    = link_to 'Copy to clipboard', '#', class: 'btn btn-primary',
                              id: 'tileToClipboard', style: 'margin: 5px;'